#!/opt/local/bin/gnuplot
# This plotiing script written by Chandan
# Use to plot band structure plot for data generated by bandstruc_script.sh code
# vaspkit band data Fermi corrected
set terminal postscript enhanced color solid lw 1.2 "Times-Roman" 24
set output "band.eps"
set key font "Times-Roman,16"
set nolabel
set notitle
set encoding utf8
#set minussign
set noxtics
set format y "%2.1f"
ef = 4.5043
nband=72
ymin=-3.0
ymax= 3.0
# Change the xtics depending upon path
X0=0.0
X1=0.710808
X2=1.71343
X3=2.89106
X4=3.5045
set yrange [ymin:ymax]
set ytics 1
set ylabel "E - E_F (eV)" font "Times-Roman,20" 
set style line 1 lt 2 lc rgb 'red'
set xtics ("Z" X0, "{/Symbol G}" X1, "X" X2, "N" X3, "Z" X4)
set arrow 100 from X0,ymin to X0,ymax nohead lc rgb "#C0C0C0"
set arrow 200 from X1,ymin to X1,ymax nohead lc rgb "#C0C0C0"
set arrow 300 from X2,ymin to X2,ymax nohead lc rgb "#C0C0C0"
set arrow 400 from X3,ymin to X3,ymax nohead lc rgb "#C0C0C0"
set arrow 500 from X4,ymin to X4,ymax nohead lc rgb "#C0C0C0"
#set xzeroaxis lt 2 lw 1 lc rgb "#A0A0A0"
band(n) = sprintf('band%d.dat', n)
plot for [i=1:nband] band(i) u ($1):($3-ef) notitle with lines lt 1 lc 0 lw 1.5,\
for [i=1:nband] band(i) u ($1):($4-ef) notitle with lines lt 1 lc rgb "#FF0000" lw 1.5
