#!/opt/local/bin/gnuplot
# This plotiing script written by Chandan
# Use to plot band structure plot for data generated by vaspkit
# vaspkit band data Fermi corrected
set terminal postscript enhanced color solid lw 1.2 "Times-Roman" 24
set output "phonon.eps"
set key font "Times-Roman,24" top center
set nolabel
set notitle
set encoding utf8
#set minussign
set noxtics
set format y "%2.1f"
ymin=-0.2
ymax= 7.0
# Change the xtics depending upon path
X0=0.0
X1=0.15219320
X2=0.30438650
X3=0.48012410
X4=0.63231730
set yrange [ymin:ymax]
set ytics 1
set ylabel "Frequency (THz)" font "Times-Roman,24" 
set style line 1 lt 2 lc rgb 'red'
set xtics ("{/Symbol G}" X0, "X" X1, "M" X2, "{/Symbol G}" X3, "R" X4)
set arrow 100 from X0,ymin to X0,ymax nohead lc rgb "#C0C0C0"
set arrow 200 from X1,ymin to X1,ymax nohead lc rgb "#C0C0C0"
set arrow 300 from X2,ymin to X2,ymax nohead lc rgb "#C0C0C0"
set arrow 400 from X3,ymin to X3,ymax nohead lc rgb "#C0C0C0"
set arrow 500 from X4,ymin to X4,ymax nohead lc rgb "#C0C0C0"
set xzeroaxis lt 2 lw 1 lc rgb "#A0A0A0"
plot 'phonon.dat' u ($1):($2) notitle with lines lt 1 lc 0 lw 1.5
