#!/opt/local/bin/gnuplot
# This plotiing script written by Chandan
# Use to plot band structure plot for data generated by vaspkit
# vaspkit band data Fermi corrected
set terminal postscript enhanced color solid lw 1.2 "Times-Roman" 24
set output "proj-UTe2.eps"
set key font "Times-Roman,24" samplen 1.2 outside top right
set nolabel
set notitle
set encoding utf8
#set minussign
set noxtics
set format y "%2.1f"
ymin=-0.2
ymax= 0.2
# Change the xtics depending upon path
X0=0.0
X1=0.788
X2=1.347
X3=2.135
X4=2.694
X5=3.14
set yrange [ymin:ymax]
set ytics 0.1
set ylabel "E - E_F (eV)" font "Times-Roman,24" 
set style line 1 lt 2 lc rgb 'red'
set xtics ("{/Symbol G}" X0, "R" X1, "T" X2, "S" X3, "{/Symbol G}" X4, "X" X5)
set arrow 100 from X0,ymin to X0,ymax nohead lc rgb "#C0C0C0"
set arrow 200 from X1,ymin to X1,ymax nohead lc rgb "#C0C0C0"
set arrow 300 from X2,ymin to X2,ymax nohead lc rgb "#C0C0C0"
set arrow 400 from X3,ymin to X3,ymax nohead lc rgb "#C0C0C0"
set arrow 500 from X4,ymin to X4,ymax nohead lc rgb "#C0C0C0"
set arrow 600 from X5,ymin to X5,ymax nohead lc rgb "#C0C0C0"
#set xzeroaxis lt 2 lw 1 lc rgb "#A0A0A0"
plot 'U.dat' u ($1):($2):($3) w p ps variable pt 7 lc 7 title 'U',\
'Te.dat' u ($1):($2):($3) w p ps variable pt 7 lc rgb "#0000FF" title "Te"
